services:
  - type: web
    name: marketingapi
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: marketingapi
      - key: JWT_SECRET
        generateValue: true
      - key: SEED_DEMO_DATA
        value: "false"
