import React, { useEffect, useState } from "react";
import api, { apiError } from "../api";
import { Bot, CalendarDays, Building2, BriefcaseBusiness, Store, Megaphone, Play, CheckCircle2 } from "lucide-react";

const ICONS = { healthcare: CalendarDays, infrastructure: Building2, b2b: BriefcaseBusiness, "small-business": Store, "social-growth": Megaphone };
export default function IndustryBots() {
 const [bots,setBots]=useState([]); const [selected,setSelected]=useState(null); const [status,setStatus]=useState("");
 useEffect(()=>{api.get("/industry-bots").then(r=>setBots(r.data.bots||[])).catch(e=>setStatus(apiError(e.response?.data?.detail)||"Could not load bots"));},[]);
 const run=async(action)=>{setStatus("Preparing action..."); try { const r=await api.post(`/industry-bots/${selected.id}/action`,{action,payload:{source:"industry-bot-workspace"}}); setStatus(`Ready: ${r.data.action}`); } catch(e){setStatus(apiError(e.response?.data?.detail)||"Action unavailable");}};
 return <div className="mx-auto w-full max-w-7xl space-y-7 px-4 py-7 sm:px-6 lg:px-8">
  <header><div className="mb-2 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.18em] text-violet-500"><Bot className="h-4 w-4"/> Smart Automation AI</div><h1 className="font-heading text-3xl font-extrabold tracking-tight text-slate-950 sm:text-4xl">Industry Agents that turn enquiries into actions.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-500 sm:text-base">Agentic workflows for healthcare, infrastructure, B2B, small business and digital growth. Connect approved channels and providers to execute real-world actions.</p></header>
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{bots.map(bot=>{const I=ICONS[bot.id]||Bot;return <button key={bot.id} onClick={()=>{setSelected(bot);setStatus("")}} className={`app-panel p-5 text-left transition hover:-translate-y-0.5 ${selected?.id===bot.id?"ring-2 ring-violet-400":""}`}><div className="flex items-start justify-between"><div className="soft-icon"><I className="h-5 w-5"/></div><span className="rounded-full bg-violet-50 px-2.5 py-1 text-[10px] font-extrabold uppercase text-violet-600">Agent</span></div><h2 className="mt-5 font-heading text-lg font-extrabold text-slate-900">{bot.name}</h2><p className="mt-2 text-xs text-slate-500">{bot.industries.join(" • ")}</p><div className="mt-4 flex flex-wrap gap-2">{bot.capabilities.map(c=><span key={c} className="rounded-lg border border-violet-100 bg-violet-50/50 px-2 py-1 text-[10px] font-bold text-violet-700">{c}</span>)}</div></button>})}</section>
  {selected&&<section className="app-panel p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-heading text-2xl font-extrabold text-slate-950">{selected.name}</h2><p className="mt-2 text-sm text-slate-500">Channels: {selected.channels.join(" • ")}</p></div>{status&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><CheckCircle2 className="h-4 w-4"/>{status}</div>}</div><h3 className="mt-7 text-sm font-extrabold text-slate-800">Available agent actions</h3><div className="mt-3 flex flex-wrap gap-2">{selected.actions.map(a=><button key={a} onClick={()=>run(a)} className="brand-gradient flex items-center gap-2 rounded-xl px-3 py-2 text-xs font-extrabold text-white shadow-brand"><Play className="h-3.5 w-3.5"/>{a.replaceAll("_"," ")}</button>)}</div></section>}
 </div>;
}
